pipeline:
  build_and_push:
    image: plugins/docker
    tag: latest
    dockerfile: Dockerfile
    repo: docker.netsoc.co/netsoc-discord-bot
    registry: docker.netsoc.co
    secrets: [ docker_username, docker_password ]
branches: master
