pipeline:
  build_and_push:
    image: plugins/docker
    tags: ${DRONE_COMMIT_BRANCH}
    dockerfile: Dockerfile
    repo: docker.netsoc.co/netsoc-discord-bot
    registry: docker.netsoc.co
    secrets: [ docker_username, docker_password ]
