/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Netsoc.Discord.Bot
import com.jessecorbett.diskord.api.*

const val BOT_TOKEN = "A-Totally-Real-Discord-Bot-Token"

suspend fun main() {
    bot(BOT_TOKEN) {
        commands {
            command("ping") {
                reply("pong")
                delete()
            }
        }
    }
}
